permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Anya Lin
  email: liuchang112133@gmail.com
  link: http://blog.feifeier.com
  weibo: http://weibo.com/Cawabunga
  github: http://github.com/feifeierchampy
  instagram: http://instagram/feifeierchampy
  music: http://site.douban.com/linanya
  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

  
# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null
# 站点信息
title: CHAMPION
description: My personal blog
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/d.png
favicon: /public/img/d.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# 多说 设置
duoshuo:
  shortname: champy

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - 
  - 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
