encoding: utf-8
permalink: /:year/:month/:day/:title
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [ "hard_wrap",
                "autolink", 
                "tables", 
                "strikethrough", 
                "superscript", 
                "with_toc_data", 
                "highlight", 
                "prettify",
                "no_intra_emphasis"]

img_path: http://7xkxii.com1.z0.glb.clouddn.com
title: LC

# kramdown:
#     auto_ids:true,
#     footnote_nr:1
#     entity_output:as_char
#     toc_levels:1..6
#     use_coderay:false



